services:
  # Directus
  - type: web
    plan: free
    name: teamhub-directus
    runtime: image
    image:
      url: docker.io/directus/directus:latest
    region: frankfurt
    envVars:
      - fromGroup: team-hub
      - key: PUBLIC_URL 
        value: https://backend.teamhub.keppni.io
      - key: DB_CLIENT
        value: pg
      - key: DB_HOST
        fromDatabase:
          name: tolli
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: teamhub_prod
      - key: DB_USER
        fromDatabase:
          name: tolli
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: tolli
          property: password
    numInstances: 1 # optional (defaults to 1)
    domains:
      - backend.teamhub.keppni.io
  - type: web
    plan: free
    region: frankfurt
    name: teamhub-app
    runtime: node
    repo: https://github.com/Tolli81/team-hub.git
    rootDir: nuxt-app
    buildCommand: yarn; yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 20.5.0
    domains:
      - teamhub.keppni.io

    autoDeploy: false # optional
