services:
  # Directus
  - type: web
    plan: free
    name: teamhub-directus
    runtime: image
    image:
      url: docker.io/directus/directus:latest
    region: frankfurt # optional (defaults to oregon)
    numInstances: 1 # optional (defaults to 1)
    envVars:
      - fromGroup: team-hub
      - key: DB_CLIENT
        value: pg
      - key: DB_HOST
        fromDatabase:
          name: tolli
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: teamhub_prod
      - key: DB_USER
        fromDatabase:
          name: tolli
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: tolli
          property: password
      - key: KEY
        generateValue: true # will generate a base64-encoded 256-bit secret
      - key: SECRET
        generateValue: true # will generate a base64-encoded 256-bit secret
  # TeamHub frontent nuxt app
  - type: web
    plan: free
    name: teamhub-app
    runtime: docker
    repo: https://github.com/Tolli81/team-hub.git
    rootDir: nuxt-app
    buildCommand: yarn install
#    startCommand: yarn run
     domains:
       - teamhub.keppni.io
    autoDeploy: false # optional

